export const ErrorCodes = {
  UNKNOWN: 'ERR_UNKNOWN',
  VALIDATION: 'ERR_VALIDATION',
  NOT_FOUND: 'ERR_NOT_FOUND',
  TIMEOUT: 'ERR_TIMEOUT',

  AUTH_REQUIRED: 'ERR_AUTH_REQUIRED',
  AUTH_EXPIRED: 'ERR_AUTH_EXPIRED',
  AUTH_INVALID: 'ERR_AUTH_INVALID',

  RATE_LIMITED: 'ERR_RATE_LIMITED',
  RATE_LIMIT_PLATFORM: 'ERR_RATE_LIMIT_PLATFORM',

  CRAWLER_FETCH_FAILED: 'ERR_CRAWLER_FETCH_FAILED',
  CRAWLER_PARSE_FAILED: 'ERR_CRAWLER_PARSE_FAILED',
  CRAWLER_BLOCKED: 'ERR_CRAWLER_BLOCKED',
  CRAWLER_CAPTCHA: 'ERR_CRAWLER_CAPTCHA',
  CRAWLER_RETRY_EXHAUSTED: 'ERR_CRAWLER_RETRY_EXHAUSTED',

  PLATFORM_UNAVAILABLE: 'ERR_PLATFORM_UNAVAILABLE',
  PLATFORM_AUTH_FAILED: 'ERR_PLATFORM_AUTH_FAILED',
  PLATFORM_API_ERROR: 'ERR_PLATFORM_API_ERROR',
  PLATFORM_APPLY_FAILED: 'ERR_PLATFORM_APPLY_FAILED',

  EXTERNAL_API_ERROR: 'ERR_EXTERNAL_API_ERROR',
  EXTERNAL_TIMEOUT: 'ERR_EXTERNAL_TIMEOUT',
  EXTERNAL_UNAVAILABLE: 'ERR_EXTERNAL_UNAVAILABLE',

  APPLICATION_DUPLICATE: 'ERR_APPLICATION_DUPLICATE',
  APPLICATION_INVALID: 'ERR_APPLICATION_INVALID',
};
