/**
 * File reading and bundling utilities for worker generation
 * @module file-reader
 */

const path = require('path');
const esbuild = require('esbuild');
const { ESCAPE_PATTERNS } = require('./config');
const { readAllFiles } = require('./file-operations');
const { buildSkillRadarData } = require('./skill-radar-data');

/**
 * Build configuration for source files loaded by the generator.
 * @param {string} baseDir - Portfolio worker directory.
 * @returns {Array<{path: string, encoding: string|null, name: string}>} File list.
 */
function getFilesToRead(baseDir) {
  return [
    {
      path: path.join(baseDir, 'index.html'),
      encoding: 'utf-8',
      name: 'indexHtmlRaw',
    },
    {
      path: path.join(baseDir, 'index-en.html'),
      encoding: 'utf-8',
      name: 'indexEnHtmlRaw',
    },
    {
      path: path.join(baseDir, 'data.json'),
      encoding: 'utf-8',
      name: 'projectDataRaw',
    },
    {
      path: path.join(baseDir, 'data_en.json'),
      encoding: 'utf-8',
      name: 'projectDataEnRaw',
    },
    {
      path: path.join(baseDir, 'data_ja.json'),
      encoding: 'utf-8',
      name: 'projectDataJaRaw',
    },
    {
      path: path.join(baseDir, 'manifest.json'),
      encoding: 'utf-8',
      name: 'manifestJson',
    },
    {
      path: path.join(baseDir, 'manifest_en.json'),
      encoding: 'utf-8',
      name: 'manifestEnJson',
    },
    {
      path: path.join(baseDir, 'sw.js'),
      encoding: 'utf-8',
      name: 'serviceWorker',
    },
    {
      path: path.join(baseDir, 'robots.txt'),
      encoding: 'utf-8',
      name: 'robotsTxt',
    },
    {
      path: path.join(baseDir, 'sitemap.xml'),
      encoding: 'utf-8',
      name: 'sitemapXml',
    },
    {
      path: path.join(baseDir, 'og-image.webp'),
      encoding: null,
      name: 'ogImageBuffer',
    },
    {
      path: path.join(baseDir, 'og-image-en.webp'),
      encoding: null,
      name: 'ogImageEnBuffer',
    },
    {
      path: path.join(baseDir, 'og-image-ja.webp'),
      encoding: null,
      name: 'ogImageJaBuffer',
      optional: true,
    },
    {
      // Generated by tools/scripts/build/pdf-generator.go (`master` variant).
      // Untracked since commit 56f9104 — may be absent on a fresh checkout.
      // The build proceeds with an empty buffer; the next CI run that produces
      // the PDF (or a local `go run ./tools/scripts/build/pdf-generator.go master`)
      // will populate it.
      path: path.join(
        baseDir,
        '..',
        '..',
        'packages',
        'data',
        'resumes',
        'master',
        'resume_final.pdf'
      ),
      encoding: null,
      name: 'resumePdfBuffer',
      optional: true,
    },
  ];
}

/**
 * Bundle main.js using esbuild and escape for template literal embedding.
 * @param {string} baseDir - Portfolio worker directory.
 * @returns {Promise<string>} Bundled and escaped JavaScript source.
 */
async function bundleMainScript(baseDir, defines = {}) {
  const bundleResult = await esbuild.build({
    entryPoints: [path.join(baseDir, 'src', 'scripts', 'main.js')],
    bundle: true,
    minify: true,
    write: false,
    format: 'iife',
    target: ['es2020'],
    absWorkingDir: baseDir,
    charset: 'utf8',
    define: defines,
  });

  return bundleResult.outputFiles[0].text
    .replace(ESCAPE_PATTERNS.BACKSLASH, '\\\\')
    .replace(ESCAPE_PATTERNS.BACKTICK, '\\`')
    .replace(ESCAPE_PATTERNS.DOLLAR, '\\$');
}

/**
 * Bundle CSS with esbuild.
 * @param {string} baseDir - Portfolio worker directory.
 * @returns {Promise<string>} Minified CSS bundle.
 */
async function bundleCss(baseDir) {
  const cssBundleResult = await esbuild.build({
    entryPoints: [path.join(baseDir, 'src', 'styles', 'main.css')],
    bundle: true,
    minify: true,
    write: false,
  });

  return cssBundleResult.outputFiles[0].text;
}

/**
 * Read all build input files and bundle dependent assets.
 * @param {{baseDir: string, logger: {log: Function}}} options - Build options.
 * @returns {Promise<Object>} Raw source payload.
 */
async function readBuildInputs({ baseDir, logger }) {
  logger.log('📂 Reading source files...');
  const filesToRead = getFilesToRead(baseDir);
  const fileContents = readAllFiles(filesToRead);

  logger.log('📦 Bundling main.js...');
  // Inject real skills from data.json into the client skill-radar widget via
  // esbuild `define`, replacing the module's stale hardcoded fallback.
  let skillRadarDefine = {};
  try {
    const projectData = JSON.parse(fileContents.projectDataRaw || '{}');
    const radarData = buildSkillRadarData(projectData.skills);
    skillRadarDefine = { __SKILL_DATA__: JSON.stringify(radarData) };
    logger.log(`✓ Injected ${Object.keys(radarData).length} skill categories into radar`);
  } catch (err) {
    logger.warn(`⚠ Skill radar injection skipped: ${err.message}`);
  }
  const mainJs = await bundleMainScript(baseDir, skillRadarDefine);

  logger.log('📦 Bundling CSS...');
  const cssContent = await bundleCss(baseDir);

  return {
    ...fileContents,
    mainJs,
    cssContent,
  };
}

module.exports = {
  readBuildInputs,
  bundleMainScript,
  bundleCss,
  getFilesToRead,
};
