// Globals the portfolio client script reads but does not import.

// apps/portfolio/lib/file-reader.js bundles the client script with an esbuild
// `define` that replaces __SKILL_DATA__ with the radar data built from the SSoT
// skills. Unbundled source has no such binding, so skill-radar-data.js guards
// it with `typeof` and falls back to its bundled copy.
declare const __SKILL_DATA__:
  Record<string, import('../../lib/skill-radar-data.js').RadarCategory> | undefined;

interface ResumeChatSkillCategory {
  title?: string;
  items?: Array<{ name?: string; level?: string }>;
}

interface Window {
  // Google Analytics, defined by a later inline script in index*.html.
  gtag?: (command: string, action: string, params?: Record<string, unknown>) => void;
  // Locale data main.js fetches from /resume-data.json (generated by
  // tools/scripts/utils/resume-web-data-generator.js); `{}` when the fetch fails.
  __RESUME_CHAT_DATA__?: {
    skills?: Record<string, ResumeChatSkillCategory>;
    careers?: unknown[];
    [key: string]: unknown;
  };
}
