/**
 * Test-time access to the content that is materialized for the build.
 *
 * Tests must not carry the owner's identity or resume copy as literals: the
 * repository is public and CI runs against a fake content pack. Read the values
 * from the same files the subject renders instead.
 *
 * - master:    packages/data/resumes/master/resume_data{,_en,_ja}.json (authoritative)
 * - portfolio: apps/portfolio/data{,_en,_ja}.json (generated by `npm run sync:data`)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const MASTER_FILES = {
  ko: 'resume_data.json',
  en: 'resume_data_en.json',
  ja: 'resume_data_ja.json',
};
const PORTFOLIO_FILES = { ko: 'data.json', en: 'data_en.json', ja: 'data_ja.json' };

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (error) {
    throw new Error(
      `Cannot read ${path.relative(ROOT, file)} (${error.message}); run "npm run sync:data" first`
    );
  }
}

function pick(files, locale) {
  const file = files[locale];
  if (!file) throw new Error(`Unsupported locale: ${locale}`);
  return file;
}

/** Authoritative resume data for a locale (ko, en, ja). */
function loadMaster(locale = 'ko') {
  return readJson(path.join(ROOT, 'packages/data/resumes/master', pick(MASTER_FILES, locale)));
}

/** Generated portfolio data for a locale (ko, en, ja). */
function loadPortfolioData(locale = 'ko') {
  return readJson(path.join(ROOT, 'apps/portfolio', pick(PORTFOLIO_FILES, locale)));
}

/** personal.{name,email,phone,github,portfolio} from the master data. */
function ownerIdentity(locale = 'ko') {
  return loadMaster(locale).personal;
}

/** Last path segment of a profile URL, e.g. https://github.com/<handle> -> <handle>. */
function profileHandle(url) {
  return new URL(url).pathname.split('/').filter(Boolean).pop();
}

/** Origin of the published site (from the portfolio contact data). */
function siteOrigin() {
  return new URL(loadPortfolioData('ko').contact.website).origin;
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

module.exports = {
  escapeRegExp,
  loadMaster,
  loadPortfolioData,
  ownerIdentity,
  profileHandle,
  siteOrigin,
};
